---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
platforms:
  - name: instance
    box: bento/debian-12
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
